### ISSUE TITLE
Basic Strategy suggest incorrect when pair

### ISSUE THREAD

**Issue by amonroe** [mhluska/blackjack-simulator#41]
chartType is based upon hand.allowSplit but playerTotal based upon hand.hasPairs.  As a result, treats J,K or similar as 10 and doubles most every time causing incorrect results.  

Candidate fix:
```
const playerTotal = Utils.clamp(
  hand.allowSplit ? hand.cards[0].value : hand.cardTotal,
  chartMin,
  chartMax
);
```

**Comment by mhluska** [comment]
Sorry I'm just seeing this now. Nice find! I will push a fix tonight.
